version: "3"
services:
  nacos:
    hostname: nacos
    container_name: nacos
    image: nacos:1.3.2
    volumes:
      - /docker/nacos-docker/example/cluster-logs/nacos1:/home/nacos/logs
      - /docker/nacos-docker/example/init.d/custom.properties:/home/nacos/init.d/custom.properties
    env_file:
      - /docker/nacos-docker/env/nacos-cluster.env
    ports:
      - "8848:8848"


